# trusty beta image has jdk8, gcc4.8.4
dist: trusty
sudo: required
# xcode8 has jdk8
osx_image: xcode8.3
# Not technically required but suppresses 'Ruby' in Job status message.
language: java

os:
  - linux

env:
  - V=0.19.2

before_install:
  - |
    URL="https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-linux-x86_64.sh"
    wget -O install.sh "${URL}"
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh
script:
  - |
    bazel \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      build \
      --local_resources=400,1,1.0 \
      --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 \
      @terraform_verifier//...
  - |
    bazel \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      build \
      --local_resources=400,1,1.0 \
      --platforms=@io_bazel_rules_go//go/toolchain:darwin_amd64 \
      @terraform_verifier//...
  - |
    bazel \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      build \
      --local_resources=400,1,1.0 \
      --platforms=@io_bazel_rules_go//go/toolchain:windows_amd64 \
      @terraform_verifier//...
notifications:
  email: false
deploy:
  provider: releases
  file:
    - "./bazel-out/darwin_amd64_stripped/hashicorp_verfier"
    - "./bazel-out/linux_amd64_pure_stripped/hashicorp_verfier"
    - "./bazel-out/windows_amd64_pure_stripped/hashicorp_verfier"
  skip_cleanup: true
  on:
    tags: true
